name       : graphviz
version    : 2.38.0
release    : 4
source     :
    - http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.38.0.tar.gz : 81aa238d9d4a010afa73a9d2a704fc3221c731e1e06577c2ab3496bdef67859e
license    : EPL-1.0
component  : multimedia.graphics
summary    : Graphviz is open source graph visualization software
description: |
    Graphviz is open source graph visualization software
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pango)
    - pkgconfig(poppler)
    - pkgconfig(xaw6)
    - ghostscript-devel
setup      : |
    %patch -p1 < $pkgfiles/ghostscript918.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/usr/lib64
    $installdir/usr/bin/dot -c
patterns   :
    - devel :
        - /usr/lib64/graphviz/*.so
