name       : graphviz
version    : 2.47.0
release    : 23
source     :
    - git|https://gitlab.com/graphviz/graphviz.git : 2.47.0
license    : EPL-1.0
component  : multimedia.graphics
clang      : yes
summary    : Graphviz is open source graph visualization software
description: |
    Graphviz is open source graph visualization software
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gts)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(pango)
    - pkgconfig(poppler)
    - pkgconfig(xaw6)
    - ghostscript-devel
    - groff
patterns   :
    - devel :
        - /usr/lib64/graphviz/*.so
setup      : |
    %patch -p1 < $pkgfiles/ghostscript918.patch
    ./autogen.sh
    sed -i "s|QMAKE = @QMAKE@|QMAKE = @QMAKE@ QMAKE_MOC=moc-qt4 QMAKE_RCC=rcc-qt4 QMAKE_UIC=uic-qt4|" cmd/gvedit/Makefile.in
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/usr/lib64
    $installdir/usr/bin/dot -c
