name       : graphviz
version    : 2.40.1
release    : 9
source     :
    - http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.40.1.tar.gz : ca5218fade0204d59947126c38439f432853543b0818d9d728c589dfe7f3a421
license    : EPL-1.0
component  : multimedia.graphics
clang      : yes
summary    : Graphviz is open source graph visualization software
description: |
    Graphviz is open source graph visualization software
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pango)
    - pkgconfig(poppler)
    - pkgconfig(QtCore)
    - pkgconfig(xaw6)
    - freeglut-devel
    - ghostscript-devel
setup      : |
    %patch -p1 < $pkgfiles/ghostscript918.patch
    sed -i "s|QMAKE = @QMAKE@|QMAKE = @QMAKE@ QMAKE_MOC=moc-qt4 QMAKE_RCC=rcc-qt4 QMAKE_UIC=uic-qt4|" cmd/gvedit/Makefile.in
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/usr/lib64
    $installdir/usr/bin/dot -c
patterns   :
    - devel :
        - /usr/lib64/graphviz/*.so
